language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

before_install:
  - java -version
  - mvn --version

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
