# For help please refer the Bukkit page: https://dev.bukkit.org/projects/unlimited-lava
configuration:
  permissions: true
  messages: true
  furnace: true
  height: 60
sources:
  three: true
  two: true
  other: false
  big: false
  lava_fall: true
  water_fall: false
  plus: true
  T: true
  ring: true
furnace:
  item: BUCKET
debug: false
