_job_base: &job_base
  working_directory: ~/unlimited-lava
  steps:
    - checkout
    - run: java -version
    - run: mvn -version
    - restore_cache:
        key: unlimited-lava-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: unlimited-lava-{{ checksum "pom.xml" }}
    - run: mvn clean package -Pmetrics

version: 2
jobs:
  jdk8:
    <<: *job_base
    docker:
      - image: maven:3-jdk-8-slim
  jdk9:
    <<: *job_base
    docker:
      - image: maven:3-jdk-9-slim
workflows:
  version: 2
  all_jdks:
    jobs:
      - jdk8
      - jdk9
