name: UnlimitedLava
main: de.xghostkillerx.unlimitedlava.UnlimitedLava
version: dev build - 0.0 - dev build
author: xGhOsTkiLLeRx
description: Ability to enjoy unlimited lava sources
website: http://bit.ly/n1Wex2