name: UnlimitedLava
main: de.xghostkillerx.unlimitedlava.UnlimitedLava
version: 1.4.1
author: xGhOsTkiLLeRx
description: Ability to enjoy unlimited lava sources
website: http://bit.ly/n1Wex2
website: http://bit.ly/pCj7v3
commands:
  unlimitedlava:
    description: Handles all the UnlimitedLava commands
    usage: /unlimitedlava help or /ulava help - to see a list of available commands
    aliases: [ulava]
permissions:
  unlimitedlava.*:
    description: Gives access to all UnlimitedLava permissions
    children:
      unlimitedlava.reload: true
      unlimitedlava.enable.*: true
      unlimitedlava.disable.*: true
      unlimitedlava.help: true
      unlimitedlava.use: true
  unlimitedlava.enable.*:
    description: Gives access to all UnlimitedLava enable commands
    children:
      unlimitedlava.enable.all: true
      unlimitedlava.enable.three: true
      unlimitedlava.enable.two: true
      unlimitedlava.enable.other: true
      unlimitedlava.enable.big: true
      unlimitedlava.enable.permissions: true
      unlimitedlava.enable.messages: true
  unlimitedlava.disable.*:
    description: Gives access to all UnlimitedLava disable commands
    children:
      unlimitedlava.disable.all: true
      unlimitedlava.disable.three: true
      unlimitedlava.disable.two: true
      unlimitedlava.disable.other: true
      unlimitedlava.disable.big: true
      unlimitedlava.disable.permissions: true
      unlimitedlava.disable.messages: true
  unlimitedlava.help:
    description: Allows you to see the help
    default: op
  unlimitedlava.reload:
    description: Allows you to reload the config
    default: op
  unlimitedlava.use:
    description: Allows you to use unlimited sources
    default: op
  unlimitedlava.enable.all:
    description: Allows you to enable all sources
    default: op
  unlimitedlava.enable.three:
    description: Allows you to enable the 3x3 source
    default: op
  unlimitedlava.enable.two:
    description: Allows you to enable the 2x2 source
    default: op
  unlimitedlava.enable.other:
    description: Allows you to enable other sources
    default: op
  unlimitedlava.enable.big:
    description: Allows you to enable big sources
    default: op
  unlimitedlava.enable.permissions:
    description: Allows you to enable permissions
    default: op
  unlimitedlava.enable.messages:
    description: Allows you to enable messages
    default: op
  unlimitedlava.disable.all:
    description: Allows you to disable all sources
    default: op
  unlimitedlava.disable.three:
    description: Allows you to disable the 3x3 source
    default: op
  unlimitedlava.disable.two:
    description: Allows you to disable the 2x2 source
    default: op
  unlimitedlava.disable.other:
    description: Allows you to disable other sources
    default: op
  unlimitedlava.disable.big:
    description: Allows you to disable big sources
    default: op
  unlimitedlava.disable.permissions:
    description: Allows you to disable permissions
    default: op
  unlimitedlava.disable.messages:
    description: Allows you to disable messages
    default: op