name: UnlimitedLava
main: de.xghostkillerx.unlimitedlava.UnlimitedLava
version: DEV - 0.0 - do not release
author: xGhOsTkiLLeRx
description: Ability to enjoy unlimited lava sources
website: http://bit.ly/n1Wex2