name: Build the plugin

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Version information
      run: |
        java -version
        mvn --version

    - name: Build with Maven
      run: mvn -DskipTests=true -B -V clean package
